apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: log-system
data:
  clickhouse.yml: |
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        uid: clickhouse-uid
        isDefault: true
        jsonData:
          host: clickhouse
          port: 9000
          username: default
          defaultDatabase: logs
          protocol: native
        secureJsonData:
          password: ""
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
  namespace: log-system
data:
  default.yml: |
    apiVersion: 1
    providers:
      - name: default
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
